withings_oauth_key: <%= ENV["withings_oauth_key"] %>
withings_oauth_secret: <%= ENV["withings_oauth_secret"] %>
coveralls_repo_token: <%= ENV["coveralls_repo_token"] %>
smtp_address: <%= ENV["smtp_address"] %>
smtp_port: <%= ENV["smtp_port"] %>
smtp_domain: <%= ENV["smtp_domain"] %>
smtp_user_name: <%= ENV["smtp_user_name"] %>
smtp_password: <%= ENV["smtp_password"] %>
action_mailer:
  default_url_options:
    host: <%= ENV["action_mailer_default_url_options_host"] %>
